package com.example.reddittoppublications

//Todo replace with your token
const val AUTHORIZATION = "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlNIQTI1NjpzS3dsMnlsV0VtMjVmcXhwTU40cWY4MXE2OWFFdWFyMnpLMUdhVGxjdWNZIiwidHlwIjoiSldUIn0.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNzIyODUyMTM3LjY1NDk5LCJpYXQiOjE3MjI3NjU3MzcuNjU0OTksImp0aSI6InFaZ3NFOXNUVWFGNnc5Q3JQd1FTYzVNVVJJR2dTZyIsImNpZCI6ImNhV0JsZFRoaHJhSWpBT2taN0ZVMnciLCJsaWQiOiJ0Ml8xNW1vemNyYXl5IiwiYWlkIjoidDJfMTVtb3pjcmF5eSIsImxjYSI6MTcyMjM1NDM0NTM3Nywic2NwIjoiZUp5S1Z0SlNpZ1VFQUFEX193TnpBU2MiLCJmbG8iOjl9.pTNC_kgnvcmQTn1dBaA3nrHDvxQ-kXF0e1r673-TGscOzgLS0fbiqKh9F4zqCoTilXSypy66Yf0o8nl3SnvVWsjRA2UqOIh2dwvMooiGRgpjns-J7nXrstXBtI_0sothPXu3RhQFAMnNgAQ7kBFCk1tp3IXvs5gLWCR_RXge-uyY9BtTBOl4Wkasp0LgwVAj-dsaHIjLzA4u_y3hX_YDkiljS8VqyoCFhiXpbnGQOY8rcbCbmUKn-9fKvSn2PrklKFr3kUgad8t57DazFWSCteO_G-qmKWhqu3Amz8ZuU_4YECEi4aSBOybsPNsLbv8zApDxtkQbI3fUnQqyfvEA2A"

fun urlCorrect(url: String): String{
    val newUrl = url.replace("&amp;", "&")
    return newUrl
}